title: "My Awesome Blog"
description: "A description of my blog"
baseurl: "" # Leave blank for root
url: "https://github.com/DhruvChopra1/Dhruv.github.io"  # Replace with your actual URL

remote_theme: mmistakes/minimal-mistakes  # Correct remote theme

# Essential plugins for remote theme functionality
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-commonmark-ghpages
  - jekyll-github-metadata
