title: "My Blog"
description: "A description of my blog"
baseurl: "" # Leave blank for the root
url: "https://<your-username>.github.io" # Replace with your GitHub Pages URL

theme: github-pages
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme # Required for remote themes
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
