title: "My Blog"
description: "A description of my blog"
baseurl: "" # Leave blank for root
url: "https://Dhruv.github.io" # Replace with your GitHub Pages URL

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
