remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
title: "Dhruv Chopra"
description: "My Portfolio"
author:
  name: "Dhruv Chopra"
  email: "1004382@pdsb.net"
baseurl: "" # Leave blank for root
url: "https://Dhruv.github.io" # Replace with your GitHub Pages URL

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Social links (optional)
social:
  twitter: yourusername
  github: yourusername
  linkedin: yourusername
