title: "My Blog"
description: "A description of my blog"
baseurl: "" # Leave blank for root
url: "https://github.com/DhruvChopra1/Dhruv.github.io"  # Replace with your actual URL

# Specify remote theme source
remote_theme: mmistakes/minimal-mistakes

# Plugins for GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-commonmark-ghpages
  - jekyll-github-metadata

# Optional configurations for customization
paginate: 5
theme: minimal-mistakes
